---
app:
  name: bamboo-app1
  metricsPort: 8081
workers:
  worker1:
    requestProducer:
      type: kafka
      kafka:
        addr: localhost:29092
        topic: topic1
    resultSubscriber:
      type: redis
      redis:
        addrs:
          - localhost:6379
  worker-redis-redis:
    requestProducer:
      type: redis
      redis:
        addrs:
          - localhost:6379
        channel: redis-redis
    resultSubscriber:
      type: redis
      redis:
        addrs:
          - localhost:6379
trace:
  exporter: jaeger
  jaeger:
    endpoint: http://localhost:14268/api/traces
shutdown:
  timeSec1: 1
  timeSec2: 1
log:
  level: debug
swagger:
  enabled: true
  host: localhost:8080
  schema: http
debug:
  ginMode: true
  # wait: true
