
---
app:
  name: bamboo-worker-redis-redis
  metricsPort: 8081
worker:
  consumer:
    type: redis
    redis:
      addrs:
        - "localhost:6379"
      channel: redis-redis
  publisher:
    type: redis
    redis:
      addrs:
        - "localhost:6379"
      password:
  numWorkers: 5
trace:
  exporter: jaeger
  jaeger:
    endpoint: http://localhost:14268/api/traces
shutdown:
  timeSec1: 1
  timeSec2: 1
log:
  level: debug
debug:
  ginMode: true
  # wait: true
