
---
app:
  name: bamboo-worker-redis-redis
  metricsPort: 8081
worker:
  kafka:
    brokers:
      - localhost:29092
    groupId: worker-redis-redis
    topic: redis-redis
  redis:
    addrs:
      - "localhost:6379"
    password:
trace:
  exporter: jaeger
  jaeger:
    endpoint: http://localhost:14268/api/traces
shutdown:
  timeSec1: 1
  timeSec2: 1
log:
  level: debug
debug:
  ginMode: true
  # wait: true
